/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ashokk' at '2/1/16 12:08 PM' with Gradle 2.7
 *
 * @author ashokk, @date 2/1/16 12:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
